<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="codeLover.local" name="testSuite.Client" tests="5" failures="1" timestamp="19 Dec 2018 04:11:15 GMT" time="11.070" errors="0">
  <testcase name="test3" time="0.127" classname="testSuite.Client"/>
  <testcase name="test2" time="0.083" classname="testSuite.Client"/>
  <testcase name="test1" time="10.718" classname="testSuite.Client"/>
  <testcase name="test4" time="0.078" classname="testSuite.Client"/>
  <testcase name="testO" time="0.064" classname="testSuite.Client">
    <failure type="java.lang.AssertionError" message="expected:&lt;401&gt; but was:&lt;200&gt;">
      <![CDATA[java.lang.AssertionError: expected:<401> but was:<200>at org.testng.AssertJUnit.fail(AssertJUnit.java:59)at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)at testSuite.Client.testO(Client.java:20)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- testO -->
</testsuite> <!-- testSuite.Client -->
